// URETILMIS DOSYA — ELLE DUZENLEME.
// Kaynak: apps/web/public/kurulum/codex.json
// Yeniden uret: scripts/gomulu-manifest-uret.sh

extension Manifest {
    static let embeddedJson =
    """
    {"schemaVersion":1,"updatedAt":"2026-09-07","note":"yzlab Codex kurucusunun okudugu canli manifest. Bu dosya STATIK olarak servis edilir (next start public/ dizinini diskten okur) — degistirmek icin BUILD veya RESTART GEREKMEZ. Model degisikligi, token alan adi degisikligi, minimum surum: hepsi burada tek satir.","api":{"baseUrl":"https://yapayzekalab.org/v1","validateUrl":"https://yapayzekalab.org/v1/balance","validateMethod":"GET","authHeader":"Authorization","authPrefix":"Bearer ","keyPrefix":"yzk_live_"},"codex":{"minVersion":"0.149.0","npmPackage":"@openai/codex","catalogUrl":"https://yapayzekalab.org/kurulum/codex-catalog.json","catalogFile":"yzlab-model-catalog.json","catalogRequired":true,"profileName":"yzlab","profileFile":"yzlab.config.toml","launchCommand":"codex -p yzlab","defaultModel":"gpt-5.6-sol","models":[{"id":"gpt-5.6-sol","label":"GPT-5.6 Sol (varsayilan)","contextWindow":450000},{"id":"gpt-6-astra","label":"GPT-6 Astra (en guclu)","contextWindow":450000},{"id":"gpt-5.6-terra","label":"GPT-5.6 Terra","contextWindow":450000},{"id":"gpt-5.6-luna","label":"GPT-5.6 Luna (ekonomik)","contextWindow":450000},{"id":"gpt-5.5","label":"GPT-5.5","contextWindow":272000}],"ballsTierContextWindow":750000,"profileTemplate":"# YapayZekaLab — Codex profili\\n# Bu dosyayi yzlab kurucusu olusturdu. Silmek = kurulumu geri almak.\\n# Kendi ChatGPT Plus ayarlarina DOKUNULMADI: config.toml ve auth.json aynen duruyor.\\n# Calistirmak icin:  codex -p yzlab\\n\\nmodel = \\"{{MODEL}}\\"\\nmodel_provider = \\"yapayzekalab\\"\\nmodel_catalog_json = \\"{{CATALOG_PATH}}\\"\\nmodel_context_window = {{CONTEXT}}\\n\\n[model_providers.yapayzekalab]\\nname = \\"YapayZekaLab\\"\\nbase_url = \\"{{BASE_URL}}\\"\\nwire_api = \\"responses\\"\\n{{TOKEN_FIELD}} = \\"{{TOKEN}}\\"\\n","tokenField":"experimental_bearer_token"},"node":{"minVersion":"20.0.0","windows":{"method":"msi","url":"https://nodejs.org/dist/v22.22.2/node-v22.22.2-x64.msi","silentArgs":"/quiet /norestart","wingetFallbackId":"OpenJS.NodeJS.LTS"},"macos":{"method":"pkg","url":"https://nodejs.org/dist/v22.22.2/node-v22.22.2.pkg","silentArgs":"-target /"}},"installer":{"latestVersion":"0.1.0","windowsUrl":"https://github.com/OWNER/yzlab-kurucu/releases/latest/download/YzlabKurucu.exe","macosUrl":"https://github.com/OWNER/yzlab-kurucu/releases/latest/download/YzlabKurucu.dmg"}}
    """
}
